[package]
name = "poseidon-zk"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff = "0.5.0-alpha.0"
ark-std = "0.5.0-alpha.0"
ark-relations = "0.5.0-alpha.0"
ark-r1cs-std = "0.5.0-alpha.0"
ark-snark = "0.5.0-alpha.0"
ark-groth16 = "0.5.0-alpha.1"
rand = "0.9.0-alpha.2"

